normalizeImages: false

optimizer:
  maximize: off
  scale:
    translation: 0.001 # What is an appropriate 2D translation scale?
    rotation: 300000
    size: 300000
  maxIterations: 1000
  regularStepGradientDescent:
    relaxationFactor: 0.93
    maxStepLength: 20
    minStepLength: 0.3
    gradientMagnitudeTolerance: 50
  # gradientDescent:
    # gradually increase learning rate from low value until it becomes unstable
    # learningRate: 0.0005

metric:
  meanSquares:

maskShrinkFactor: 0.75
