maskShrinkFactor: 0.75
normalizeImages: true

optimizer:
  maximize: on
  scale:
    translation: 0.00005 # What is an appropriate 2D translation scale?
    rotation: 100
    size: 100
  maxIterations: 20
  # uncomment name of optimizer you wish to use
  # regularStepGradientDescent:
  #   relaxationFactor: 0.8
  #   maxStepLength: 10
  #   minStepLength: 0.01
  #   gradientMagnitudeTolerance: 0.001
  gradientDescent:
    # gradually increase learning rate from low value until it becomes unstable
    learningRate: 0.2

metric:
  # uncomment name of metric you wish to use
  # set maximise: on with normalizedCorrelation, off for mattesMutualInformation,
  # meanSquares should be minimized if dark corresponds to dark, light to light.
  # meanSquares:
  normalizedCorrelation:
  # mattesMutualInformation:
  #   # numberOfSpatialSamples: 24000
  #   numberOfSpatialSamples: 10000
  #   numberOfHistogramBins: 100 # Number of bins recommended to be about 50, see ITK Software Guide p341
