optimizerTranslationScale3D: 15000.0
optimizerTranslationScale2D: 15000.0 # What is an appropriate 2D translation scale?
maxIterations: [2, 2, 2, 2]
stackSpacings: [70.4, 70.4, 160] # Not implemented yet