ActualLoResSpacings: [19, 19, 10] # LoRes spacings
ActualHiResSpacings:  [0.546, 0.546, 10]
LoResSpacings: [152, 152, 10] # LoRes spacings
HiResSpacings:  [70.4, 70.4, 10]
LoResSize: [89, 114]
LoResOffset: [17000, 2200]

optimizer:
  translationScale: 0.001 # What is an appropriate 2D translation scale?
  maxIterations: 20 # 400
  # uncomment name of optimizer you wish to use
  regularStepGradientDescent:
    relaxationFactor: 0.99
    maxStepLength: 0.3 # Dubious numbers
    minStepLength: 0.001 # Dubious numbers
  # gradientDescent:
    # gradually increase learning rate from low value until it becomes unstable
    # learningRate: 10

metric:
  meanSquares:
  # mattesMutualInformation:
    # numberOfSpatialSamples: 24000
    # numberOfSpatialSamples: 10000
    # numberOfHistogramBins: 50 # Number of bins recommended to be about 50, see ITK Software Guide p341
