stackSpacings: [70, 70, 10] # LoRes spacings
HiResSpacings:  [0.546, 0.546, 10]
optimizerTranslationScale2D: 15000.0 # What is an appropriate 2D translation scale?
maxIterations2D: 100 # Dubious numbers
maxStepLength2D: 0.1 # Dubious numbers
minStepLength2D: 0.001 # Dubious numbers
