ActualLoResSpacings: [19, 19, 10] # LoRes spacings
ActualHiResSpacings:  [0.546, 0.546, 10]
LoResSpacings: [152, 152, 10] # LoRes spacings
HiResSpacings:  [70.4, 70.4, 10]
LoResSize: [89, 114]
LoResOffset: [17000, 2200]
# optimizerTranslationScale: 0.0000015 # What is an appropriate 2D translation scale?
optimizerTranslationScale: 0.001 # What is an appropriate 2D translation scale?
maxIterations: 300 # Dubious numbers
maxStepLength: 0.1 # Dubious numbers
minStepLength: 0.001 # Dubious numbers
relaxationFactor: 0.6
# numberOfSpatialSamples: 24000
numberOfSpatialSamples: 10000
numberOfHistogramBins: 50 # Number of bins recommended to be about 50, see ITK Software Guide p341
maximizeOn: true
