--- 
:Slack0001: 
  :flipped: true
:Slack0017: 
  :flipped: true
:Slack0033: 
  :flipped: true
:Slack0049: 
  :flipped: true
:Slack0065: 
  :flipped: true
:Slack0081: 
  :flipped: true
:Slack0097: 
  :flipped: true
:Slack0112: 
  :flipped: true
:Slack0113: 
  :description: Slightly damaged on top edge
  :flipped: true
:Slack0129: 
  :flipped: true
:Slack0145: 
  :flipped: true
:Slack0161: 
  :flipped: true
:Slack0176:
  :flipped: true
:Slack0193: 
  :flipped: true
:Slack0209:
  :flipped: true
:Slack0225: 
  :flipped: true
:Slack0305:
  :flipped: true
:Slack0385: 
  :flipped: true
:Slack0401:
  :flipped: true
:Slack0561:
  :description: Completely rubbered
:Slack0641: 
  :description: Completely rubbered
:Slack0785:
  :description: File corrupted
  :ignore: true
:Slack1152:
  :description: Folding in papillary muscle
:Slack1169:
  :description: Folding in papillary muscle
:Slack1185:
  :description: Folding in papillary muscle
:Slack1200:
  :description: Folding in papillary muscle
:Slack1217:
  :description: Folding in papillary muscle
:Slack1249:
  :description: Folding in papillary muscle
:Slack1265:
  :description: Folding in papillary muscle
:Slack1281:
  :description: Folding in papillary muscle
:Slack1313:
  :description: Folding in papillary muscle
:Slack1329:
  :description: Empty file
:Slack1392:
  :description: A few small bubbles on surface of image
:Slack1393:
  :description: Bubbles on surface of image
:Slack1394:
  :description: Small folding at top middle
:Slack1489:
  :description: Some folding lines
:Slack1535:
  :description: Slight blue discolouration in top left area
:Slack1536:
  :description: Discoloured stripe from top left to bottom right
:Slack1537: 
  :description: Damaged on bottom end (right of image)
:Slack1538:
  :description: Slighty faded, with small blue bubbles
:Slack1539:
  :description: Several blue blotches in the top half
:Slack1617:
  :description: Small blue blotch in top middle
 