optimizer:
  maximize: off
  scale:
    translation: 0.0001 # What is an appropriate 2D translation scale?
    # rotation: 6000
    size: 60000
  maxIterations: 10
  # regularStepGradientDescent:
  #   relaxationFactor: 0.8
  #   maxStepLength: 0.05
  #   minStepLength: 0.0001
  #   gradientMagnitudeTolerance: 0.0001
  gradientDescent:
    # gradually increase learning rate from low value until it becomes unstable
    learningRate: 0.004

metric:
  meanSquares:

maskShrinkFactor: 0.75
